// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatasSolidaras.Infra.Contexts;

#nullable disable

namespace PatasSolidaras.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250618150732_AddDoacoesAndCampaingsReference")]
    partial class AddDoacoesAndCampaingsReference
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("PatasSolidarias.Domain.Entities.Campanha.Campanha", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataProgressao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IdOng")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MetaArrecadacao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Progresso")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Campanhas");
                });

            modelBuilder.Entity("PatasSolidarias.Domain.Entities.Doacoes.Doacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCampanha")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdDoador")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetodoPagamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdCampanha");

                    b.HasIndex("IdDoador");

                    b.ToTable("Doação", (string)null);
                });

            modelBuilder.Entity("PatasSolidarias.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoDataHora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioTipoId")
                        .HasMaxLength(15)
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioTipoId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("PatasSolidarias.Domain.Entities.UsuarioTipo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UsuarioTipo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Nome = "Doador"
                        },
                        new
                        {
                            Id = 1,
                            Nome = "Ajudante"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "ONG"
                        });
                });

            modelBuilder.Entity("PatasSolidarias.Domain.Entities.Doacoes.Doacao", b =>
                {
                    b.HasOne("PatasSolidarias.Domain.Entities.Campanha.Campanha", null)
                        .WithMany("Doacoes")
                        .HasForeignKey("IdCampanha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PatasSolidarias.Domain.Entities.Usuario", null)
                        .WithMany("Doacoes")
                        .HasForeignKey("IdDoador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PatasSolidarias.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("PatasSolidarias.Domain.Entities.UsuarioTipo", "UsuarioTipo")
                        .WithMany()
                        .HasForeignKey("UsuarioTipoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UsuarioTipo");
                });

            modelBuilder.Entity("PatasSolidarias.Domain.Entities.Campanha.Campanha", b =>
                {
                    b.Navigation("Doacoes");
                });

            modelBuilder.Entity("PatasSolidarias.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Doacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
